"""Sync frontend doc type constants from backend canonical catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _to_ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    backend_root = Path(__file__).resolve().parents[1]
    repo_root = backend_root.parent
    frontend_constants_path = repo_root / "frontend" / "src" / "utils" / "constants.ts"

    sys.path.insert(0, str(backend_root))
    from app.prompts.doc_types_catalog import DOC_TYPE_GROUPS  # noqa: PLC0415

    lines: list[str] = [
        "// Auto-generated by backend/scripts/sync_doc_types_to_frontend.py",
        "// Do not edit manually.",
        "",
        "export interface DocTypeGroup {",
        "  id: string",
        "  label: string",
        "  options: string[]",
        "}",
        "",
        "export const DOC_TYPE_GROUPS: DocTypeGroup[] = [",
    ]

    for group in DOC_TYPE_GROUPS:
        group_id = str(group["id"])
        group_label = str(group["label"])
        options = [str(item) for item in group["doc_types"]]
        options_ts = ", ".join(_to_ts_string(option) for option in options)

        lines.extend(
            [
                "  {",
                f"    id: {_to_ts_string(group_id)},",
                f"    label: {_to_ts_string(group_label)},",
                f"    options: [{options_ts}],",
                "  },",
            ],
        )

    lines.extend(
        [
            "]",
            "",
            "export const DOC_TYPES = DOC_TYPE_GROUPS.flatMap(group => group.options)",
            "",
        ],
    )

    frontend_constants_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Synced doc type constants -> {frontend_constants_path}")


if __name__ == "__main__":
    main()
