"""baseline"""

revision = 'a72f14d61789'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.execute(
        sa.text(
            "INSERT INTO accounts (id, code, name, status, created_at, updated_at) "
            "SELECT 1, 'default', 'default', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP "
            "WHERE NOT EXISTS (SELECT 1 FROM accounts WHERE id = 1)"
        )
    )

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('book_import_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rebuild', sa.Boolean(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('completed_files', sa.Integer(), nullable=True),
    sa.Column('failed_files', sa.Integer(), nullable=True),
    sa.Column('partial_files', sa.Integer(), nullable=True),
    sa.Column('skipped_files', sa.Integer(), nullable=True),
    sa.Column('running_file', sa.String(length=500), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('completed_chunks', sa.Integer(), nullable=True),
    sa.Column('ocr_used_files', sa.Integer(), nullable=True),
    sa.Column('ocr_pages', sa.Integer(), nullable=True),
    sa.Column('file_results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_import_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_import_tasks_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_book_import_tasks_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('ix_book_import_tasks_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('uq_book_import_tasks_task_id', ['task_id'], unique=True)

    op.create_table('book_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=500), nullable=False),
    sa.Column('source_path', sa.String(length=1200), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('file_ext', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_sources_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_book_sources_account_updated_at', ['account_id', 'updated_at'], unique=False)
        batch_op.create_index('ix_book_sources_status', ['status'], unique=False)
        batch_op.create_index('ix_book_sources_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('uq_book_sources_account_source_hash', ['account_id', 'source_hash'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_roles_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('uq_roles_account_code', ['account_id', 'code'], unique=True)

    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.JSON(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'doc_type', 'feature_name', name='uq_account_style_doc_feature')
    )
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_style_profiles_account_doctype', ['account_id', 'doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_profiles_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_style_profiles_doctype', ['doc_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account_id'), ['account_id'], unique=False)

    op.create_table('account_invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash', name='uq_invite_code_hash')
    )
    with op.batch_alter_table('account_invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_invite_codes_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invite_codes_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invite_codes_used_by'), ['used_by'], unique=False)
        batch_op.create_index('ix_invite_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('ix_invite_expires_at', ['expires_at'], unique=False)

    op.create_table('book_style_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('origin_ref', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['book_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_style_rules', schema=None) as batch_op:
        batch_op.create_index('ix_book_style_rules_account_doc_rule', ['account_id', 'doc_type', 'rule_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_style_rules_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_book_style_rules_doc_type_rule_type', ['doc_type', 'rule_type'], unique=False)
        batch_op.create_index('ix_book_style_rules_source_id', ['source_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ov_session_id', sa.String(length=100), nullable=True),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_chat_sessions_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_chat_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chat_sessions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index('ix_materials_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_materials_user_doctype', ['user_id', 'doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_role_permissions_permission_id', ['permission_id'], unique=False)
        batch_op.create_index('ix_role_permissions_role_id', ['role_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_key', sa.String(length=100), nullable=False),
    sa.Column('pref_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', 'pref_key', name='uq_account_user_pref_key')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('ix_user_roles_role_id', ['role_id'], unique=False)
        batch_op.create_index('ix_user_roles_user_id', ['user_id'], unique=False)

    op.create_table('writing_habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_type', sa.String(length=50), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_habits', schema=None) as batch_op:
        batch_op.create_index('ix_habits_account_type', ['account_id', 'habit_type'], unique=False)
        batch_op.create_index('ix_habits_user_type', ['user_id', 'habit_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_habits_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_habits_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_chat_messages_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('docx_file_path', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_doc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['parent_doc_id'], ['generated_documents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.create_index('ix_gendocs_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index('ix_gendocs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_user_id'), ['user_id'], unique=False)

    op.create_table('session_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_json', sa.JSON(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('session_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_drafts_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_session_drafts_account_updated', ['account_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_drafts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_session_drafts_user_updated', ['user_id', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_session_drafts_user_updated')
        batch_op.drop_index(batch_op.f('ix_session_drafts_user_id'))
        batch_op.drop_index('ix_session_drafts_account_updated')
        batch_op.drop_index(batch_op.f('ix_session_drafts_account_id'))

    op.drop_table('session_drafts')
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_session_id'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_account_id'))
        batch_op.drop_index('ix_gendocs_user_created')
        batch_op.drop_index('ix_gendocs_account_created')

    op.drop_table('generated_documents')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index('ix_chat_messages_session_created')
        batch_op.drop_index(batch_op.f('ix_chat_messages_account_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('writing_habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_habits_user_id'))
        batch_op.drop_index(batch_op.f('ix_writing_habits_account_id'))
        batch_op.drop_index('ix_habits_user_type')
        batch_op.drop_index('ix_habits_account_type')

    op.drop_table('writing_habits')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_user_roles_user_id')
        batch_op.drop_index('ix_user_roles_role_id')

    op.drop_table('user_roles')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_account_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_role_permissions_role_id')
        batch_op.drop_index('ix_role_permissions_permission_id')

    op.drop_table('role_permissions')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_user_id'))
        batch_op.drop_index('ix_materials_user_doctype')
        batch_op.drop_index('ix_materials_user_created')
        batch_op.drop_index(batch_op.f('ix_materials_doc_type'))
        batch_op.drop_index(batch_op.f('ix_materials_account_id'))
        batch_op.drop_index('ix_materials_account_created')

    op.drop_table('materials')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index('ix_chat_sessions_user_created')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_account_id'))
        batch_op.drop_index('ix_chat_sessions_account_created')

    op.drop_table('chat_sessions')
    with op.batch_alter_table('book_style_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_book_style_rules_source_id')
        batch_op.drop_index('ix_book_style_rules_doc_type_rule_type')
        batch_op.drop_index(batch_op.f('ix_book_style_rules_account_id'))
        batch_op.drop_index('ix_book_style_rules_account_doc_rule')

    op.drop_table('book_style_rules')
    with op.batch_alter_table('account_invite_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_invite_expires_at')
        batch_op.drop_index('ix_invite_account_status')
        batch_op.drop_index(batch_op.f('ix_account_invite_codes_used_by'))
        batch_op.drop_index(batch_op.f('ix_account_invite_codes_created_by'))
        batch_op.drop_index(batch_op.f('ix_account_invite_codes_account_id'))

    op.drop_table('account_invite_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_account_id'))

    op.drop_table('users')
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_style_profiles_doctype')
        batch_op.drop_index(batch_op.f('ix_style_profiles_account_id'))
        batch_op.drop_index('ix_style_profiles_account_doctype')

    op.drop_table('style_profiles')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('uq_roles_account_code')
        batch_op.drop_index('ix_roles_account_status')
        batch_op.drop_index(batch_op.f('ix_roles_account_id'))

    op.drop_table('roles')
    with op.batch_alter_table('book_sources', schema=None) as batch_op:
        batch_op.drop_index('uq_book_sources_account_source_hash')
        batch_op.drop_index('ix_book_sources_updated_at')
        batch_op.drop_index('ix_book_sources_status')
        batch_op.drop_index('ix_book_sources_account_updated_at')
        batch_op.drop_index(batch_op.f('ix_book_sources_account_id'))

    op.drop_table('book_sources')
    with op.batch_alter_table('book_import_tasks', schema=None) as batch_op:
        batch_op.drop_index('uq_book_import_tasks_task_id')
        batch_op.drop_index('ix_book_import_tasks_updated_at')
        batch_op.drop_index('ix_book_import_tasks_account_status')
        batch_op.drop_index(batch_op.f('ix_book_import_tasks_account_id'))

    op.drop_table('book_import_tasks')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
