// Auto-generated by backend/scripts/sync_doc_types_to_frontend.py
// Do not edit manually.

export interface DocTypeGroup {
  id: string
  label: string
  options: string[]
}

export const DOC_TYPE_GROUPS: DocTypeGroup[] = [
  {
    id: "official",
    label: "公务类文书",
    options: ["决定", "公告", "通告", "意见", "通知", "通报", "报告", "请示", "批复", "函", "会议纪要"],
  },
  {
    id: "affairs",
    label: "事务类文书",
    options: ["规划", "计划", "安排", "总结", "声明", "启事", "简报", "述职报告"],
  },
  {
    id: "regulation",
    label: "规章类文书",
    options: ["章程", "条例", "办法", "规定", "细则", "守则", "制度"],
  },
  {
    id: "meeting",
    label: "会议类文书",
    options: ["讲话稿", "演讲词", "开幕词", "闭幕词", "会议记录", "心得体会"],
  },
  {
    id: "economic",
    label: "经济类文书",
    options: ["市场调查报告", "商业计划书", "可行性分析报告", "经济合同", "广告文案", "招标书", "投标书", "清算报告", "破产申请书"],
  },
  {
    id: "trade",
    label: "贸易类文书",
    options: ["合作意向书", "询价函", "报价函", "订购函", "催款函", "索赔函", "理赔函"],
  },
  {
    id: "legal",
    label: "法律类文书",
    options: ["起诉状", "上诉状", "申诉状", "答辩状", "委托书", "担保书"],
  },
  {
    id: "letters",
    label: "书信类文书",
    options: ["证明信", "介绍信", "推荐信", "感谢信", "公开信", "慰问信", "表扬信", "批评信", "倡议书"],
  },
  {
    id: "notes",
    label: "条据类文书",
    options: ["留言条", "请假条", "借条", "收条", "欠条", "发条", "领条"],
  },
  {
    id: "etiquette",
    label: "礼仪类文书",
    options: ["贺信（电）", "邀请书", "颁奖词", "欢迎词", "欢送词", "祝酒词", "答谢词", "讣告", "悼词"],
  },
  {
    id: "fallback",
    label: "其他",
    options: ["其他"],
  },
]

export const DOC_TYPES = DOC_TYPE_GROUPS.flatMap(group => group.options)
